name: Create GitHub Release

on:
  push:
    tags:
      - "*"
  workflow_dispatch: 

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add accessibility to eleventy
        run: cp accessibility/_accessibility.scss eleventy/src/_styles/_accessibility.scss
      
      - name: Create zip files
        run: zip -r accessibility.zip accessibility/ && zip -r eleventy.zip eleventy/ 

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            accessibility.zip
            eleventy.zip
